package app

import (
	"context"
	"database/sql"
	"errors"
	"time"
)

// CompleteRemoteUpload applies an authenticated storage-node result to the
// control-plane metadata. Repeated delivery of the same terminal result is
// intentionally idempotent so a storage outbox can retry until acknowledged.
func (store *Store) CompleteRemoteUpload(ctx context.Context, id, nodeID, status, sha256Value, detail string) error {
	return store.CompleteRemoteUploadPlacement(ctx, id, nodeID, id, StoragePlacementVersionV1,
		status, sha256Value, detail)
}

// CompleteRemoteUploadPlacement applies protocol-v1 terminal state only when
// node, storage key and placement version all match. The successful transition
// increments storage_version, so an exact outbox retry is idempotent while a
// stale event from an older placement is rejected.
func (store *Store) CompleteRemoteUploadPlacement(ctx context.Context, id, nodeID, storageKey string,
	storageVersion int64, status, sha256Value, detail string) error {
	if id == "" || nodeID == "" || storageKey == "" || storageVersion < StoragePlacementVersionV1 ||
		(status != "ready" && status != "blocked" && status != "quarantined") {
		return ErrConflict
	}
	tx, err := store.db.BeginTx(ctx, nil)
	if err != nil {
		return err
	}
	defer tx.Rollback()

	var current, currentKind, currentNodeID, currentKey, currentSHA256 string
	var currentVersion int64
	if err := tx.QueryRowContext(ctx, `SELECT status,storage_kind,storage_node_id,storage_key,storage_version,sha256
		FROM uploads WHERE id=?`, id).Scan(&current, &currentKind, &currentNodeID, &currentKey,
		&currentVersion, &currentSHA256); err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return ErrNotFound
		}
		return err
	}
	if currentKind != StorageKindNode || currentNodeID != nodeID || currentKey != storageKey {
		return ErrConflict
	}
	commitTerminal := func() error {
		if err := settleUploadTrafficTx(ctx, tx, id, time.Now().Unix()); err != nil {
			return err
		}
		if status == "blocked" {
			if err := releaseUploadStorageTx(ctx, tx, id); err != nil && !errors.Is(err, ErrNotFound) {
				return err
			}
		}
		return tx.Commit()
	}
	if current == status {
		// scan_detail is explanatory metadata and may be regenerated by an
		// outbox retry. Terminal identity is status + digest at the same
		// placement version; a different digest remains a hard conflict.
		if currentSHA256 != sha256Value {
			return ErrConflict
		}
		if currentVersion == storageVersion {
			// A marker-era process can be rolled back briefly while the v4
			// schema remains. Its terminal update does not know about the new
			// version column, so normalize that one legacy state atomically.
			result, err := tx.ExecContext(ctx, `UPDATE uploads SET temp_path='',object_path='',storage_version=storage_version+1
				WHERE id=? AND status=? AND storage_kind='node' AND storage_node_id=? AND storage_key=? AND storage_version=? AND sha256=?`,
				id, status, nodeID, storageKey, storageVersion, sha256Value)
			if err != nil {
				return err
			}
			if rows, _ := result.RowsAffected(); rows != 1 {
				return ErrConflict
			}
			return commitTerminal()
		}
		if currentVersion != storageVersion+1 {
			return ErrConflict
		}
		return commitTerminal()
	}
	if current != "uploading" && current != "uploaded" && current != "scanning" {
		return ErrConflict
	}
	if currentVersion != storageVersion {
		return ErrConflict
	}

	now := time.Now().Unix()
	switch status {
	case "ready":
		result, err := tx.ExecContext(ctx, `UPDATE uploads SET status='ready',offset=length,temp_path='',object_path='',sha256=?,scan_detail=?,completed_at=?,storage_version=storage_version+1
			WHERE id=? AND status IN ('uploading','uploaded','scanning') AND storage_kind='node' AND storage_node_id=? AND storage_key=? AND storage_version=?`,
			sha256Value, detail, now, id, nodeID, storageKey, storageVersion)
		if err != nil {
			return err
		}
		if rows, _ := result.RowsAffected(); rows != 1 {
			return ErrConflict
		}
	case "quarantined":
		result, err := tx.ExecContext(ctx, `UPDATE uploads SET status='quarantined',offset=length,temp_path='',object_path='',sha256=?,scan_detail=?,completed_at=?,storage_version=storage_version+1
			WHERE id=? AND status IN ('uploading','uploaded','scanning') AND storage_kind='node' AND storage_node_id=? AND storage_key=? AND storage_version=?`,
			sha256Value, detail, now, id, nodeID, storageKey, storageVersion)
		if err != nil {
			return err
		}
		if rows, _ := result.RowsAffected(); rows != 1 {
			return ErrConflict
		}
	case "blocked":
		result, err := tx.ExecContext(ctx, `UPDATE uploads SET status='blocked',offset=length,temp_path='',object_path='',sha256=?,scan_detail=?,completed_at=?,storage_version=storage_version+1
			WHERE id=? AND status IN ('uploading','uploaded','scanning') AND storage_kind='node' AND storage_node_id=? AND storage_key=? AND storage_version=?`,
			sha256Value, detail, now, id, nodeID, storageKey, storageVersion)
		if err != nil {
			return err
		}
		if rows, _ := result.RowsAffected(); rows != 1 {
			return ErrConflict
		}
	}
	return commitTerminal()
}

func (store *Store) ReservationUsesRemoteNode(ctx context.Context, reservationID, nodeID string) (bool, error) {
	var storageKind, storageNodeID, storageKey, uploadID string
	err := store.db.QueryRowContext(ctx, `SELECT u.storage_kind,u.storage_node_id,u.storage_key,u.id
		FROM download_reservations d JOIN uploads u ON u.id=d.upload_id WHERE d.id=?`, reservationID).
		Scan(&storageKind, &storageNodeID, &storageKey, &uploadID)
	if errors.Is(err, sql.ErrNoRows) {
		return false, ErrNotFound
	}
	if err != nil {
		return false, err
	}
	return storageKind == StorageKindNode && storageNodeID == nodeID && storageKey == uploadID, nil
}
